package main

import (
	"bufio"
	"fmt"
	"os"
	"strings"
)

func startRepl() {
	// Blocks the code and waits for input,
	// once the user types something and presses enter,
	// the code continues and the input is available in the returned scanner.
	scanner := bufio.NewScanner(os.Stdin)

	for {
		fmt.Print("Pokedex > ")
		scanner.Scan()
		// Text returns the most recent token generated by a call to
		// Scanner.Scan as a newly allocated string holding its bytes.
		input := cleanInput(scanner.Text())
		if len(input) == 0 {
			continue
		}

		command := input[0]

		fmt.Printf("Your command was: %v\n", command)
	}
}

func cleanInput(text string) []string {
	lower := strings.ToLower(text)
	clean := strings.Fields(lower)
	return clean
}
